name: CI
on:
  push:
    branches: [ develop ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install texlive
        run: sudo apt install texlive-base 
      - name: Install extra fonts
        run: sudo apt install texlive-fonts-extra
      - name: Install texlive-latex-extra
        run: sudo apt-get install texlive-latex-extra
      - name: Build pdf
        run: pdflatex exp.tex -o output/my_awesome_cv.pdf
      - name: Create pull request
        uses: peter-evans/create-pull-request@v3
        with: 
          commit-message: pdflatex build
          branch: pdflatex_build
          title: '[CI] pdflatex build'
